### ISSUE TITLE
BuyUSStock 에서 시장가 주문이 가능한가요?

### ISSUE THREAD

**Issue by dongju8679** [pjueon/eFriendPy#2]
시장가로 주문할려는데, 안되는것처럼 보이는데요. 혹시 시장가 로 주문이 가능한지 아시나요?

BuyUSStock(account, marketCode, productCode, amount, price)

def BuyUSStock(self, account, marketCode, productCode, amount, price):
        """미국주식 매수, marketCode: 해외거래소코드(NASD / NYSE / AMEX 등 4글자 문자열)"""
        self.SetAccountInfo(account)
        self._core.SetSingleData(3, marketCode)
        self._core.SetSingleData(4, productCode)
        self._core.SetSingleData(5, str(amount))
        self._core.SetSingleData(6, "{0:.2f}".format(price))    # 소숫점 2자리까지로 설정해야 오류가 안남
        self._core.SetSingleData(9, "0")                        # 주문서버구분코드, 0으로 입력
        self._core.SetSingleData(10, "00")                      # 주문구분, 00: 지정가
        # self._core.SetSingleData(10, "01")                      # 주문구분, 00: 지정가
        self._core.RequestData("OS_US_BUY")                     # 미국매수 주문

        orderNum = self._core.GetSingleData(1, 0)
        return orderNum

**Comment by pjueon** [comment]
공식 PDF 메뉴얼에는 미국주식에 대해서 시장가 거래에 대한 옵션이 안나와있던것으로 기억합니다. 
저 같은 경우는 그냥 현재 가격에 +-5% 정도 해서 무조건 체결되도록 구현해서 쓰고 있습니다.

한국투자증권 고객의 소리를 통해서 Open API에 대해 질문을 보내보시면
(ex> 미국주식을 시장가로 매매하려면  SetSingleData에서 주문구분을 어떤 값으로 설정해야 하는지)
아마 답변을 받으실 수  있을겁니다.
